Herwerken filestructuur (#59)
.
* reorganize

* action: fix (?)

* use cache again

* SPC/oefeningen_bart

* integrate preamble into xmPreamble

* define \logo (otherwise only in xourse)

* put logo in global.sty

* fix loading global.sty at begindocument  (needed for all of xmPrintstyle?)

* add logo SPC

* rename files kin/dyn

* compile kinematica_1dim

* toevoegen kinematica_basisbegrippen

* fix path

* obsolete semester1.tex

* skip cache

* compile folder SPC

* cleanup actions

* cleanup old xourses

* skip logo

* only kinematica_basis; fix logo

* kinematica* cursussen

* fix voorpagina; toch zonder cache

* nu dan zonder cache

* add veryclean

* hack: add frost to bake .step ..

* geknoei

diff --git a/.github/workflows/serve-ximera.yml b/.github/workflows/serve-ximera.yml
--- a/.github/workflows/serve-ximera.yml
+++ b/.github/workflows/serve-ximera.yml
@@ -1,101 +1,182 @@
-name: Ximera Workflow
-
+name: "Ximera Workflow"
 on:
-  push:      
-    branches:
-      -'neverever'
+  push:
+    # branches:
+    #     - 'main'
+
+env:
+  TEXMFHOME: /root/texmf     # Should be set in xmlatex !  
+  GPG_KEY: ${{ secrets.GPG_KEY }}
+  GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
+  XIMERA_URL: ${{ vars.XIMERA_URL }}
+  XIMERA_NAME: ${{ vars.XIMERA_NAME }}*${{ github.ref_name }}
+  # XM_TO_PROCESS: "."
+  # XM_TO_PROCESS: "test.tex SPC/vectoren.tex SPC/kinematica_basis.tex SPC/kinematica_1dim.tex"
+  XM_TO_PROCESS: "test.tex SPC/kinematica_*.tex"
 
 jobs:
-  build-ximera:
-    name: Build and preview Ximera Courses
+  build-ximera-htmlexport:
+    name: Run pdfexport and htmlexport
     runs-on: ubuntu-latest
-
+    # continue-on-error: true
+    container: &build-container
+      image: ghcr.io/ximeraproject/ximeralatex:v2.7.xmcss-full
+      options: >-
+        --workdir /code
     permissions:
       actions: read
       contents: read
       packages: write
 
     steps:
+      - name: "Prepare: Checkout code"
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      # Restore cache for cross-run speedup
+      - name: "Prepare: Restore cache"
+        uses: actions/cache/restore@v4
+        with:
+          path: |
+            **/*.pdf
+            **/*.html
+            **/*.aux
+            **/*.log
+            **/*.toc
+            **/*.xref
+            **/*.svg
+            **/*.png
+            **/*.xbb
+            !.git/**
+            !.github/**
+          key: ximeraPDFexport-${{ github.ref_name }}-${{ github.run_id }}
+          restore-keys: |
+            # ximeraHTMLexport-${{ github.ref_name }}-
+            # ximeraPDFexport-${{ github.ref_name }}-
+            # ximeraHTMLexport-
+            # ximeraPDFexport-
+
+      - name: "XIMERA: pdf and html (tikzexternalize/html)"
+        run: |
+          git config --global --add safe.directory "$GITHUB_WORKSPACE"
+          # xmlatex veryclean  -j 5 $XM_TO_PROCESS
+          # echo "kinematica:"
+          # ls -alR kinematica
+          # rm -rf */*/build
+          # rm -rf */*/xmPictures
+          # rm -rf */build
+          # rm -rf */xmPictures
+          echo "START"
+          xmlatex bake --compile pdfexport  -j 5 $XM_TO_PROCESS
+          xmlatex bake --compile htmlexport -j 5 $XM_TO_PROCESS
+          xmlatex bake --compile handout.pdf -f -j 5 $XM_TO_PROCESS
+          xmlatex frost $XM_TO_PROCESS || echo "FROST FAILED"
+          ls -alR
+          # rm -rf */*/build
+          # rm -rf */*/xmPictures
+          # rm -rf */build
+          # rm -rf */xmPictures          
+
+      # Save cache
+      - name: "Postprocess: Save cache"
+        uses: actions/cache/save@v4
+        with:
+          path: |
+            **/*.pdf
+            **/*.html
+            **/*.aux
+            **/*.log
+            **/*.toc
+            **/*.xref
+            **/*.svg
+            **/*.png
+            **/*.xbb
+            !.git/**
+            !.github/**
+          key: ximeraHTMLexport-${{ github.ref_name }}-${{ github.run_id }}
+
+      # Upload artifact
+      - name: "Postprocess: Save artifacts"
+        uses: actions/upload-artifact@v4
+        with:
+          name: htmlexport
+          path: .
+
+  serve-ximera-preview:
+    name: "Run serve for (automatic) preview version"
+    needs: build-ximera-htmlexport
+    # continue-on-error: true
+    runs-on: ubuntu-latest
+    container: &serve-container
+      image: ghcr.io/ximeraproject/ximeralatex:v2.7.xmcss
+    permissions:
+      actions: read
+      contents: read
+      packages: write
+
+    steps:
+      - name: "Prepare: Checkout code"
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      # Download artifact from previous job
+      - name: "Prepare: Checkout artifacts (from previous step)"
+        uses: actions/download-artifact@v4
+        with:
+          name: htmlexport
+          path: .
+
+      - name: "XIMERA: Serve PREVIEW version to ximeraserver"
+        run: |
+          echo "Serving to $XIMERA_URL$XIMERA_NAME"
+          git config --global --add safe.directory "$GITHUB_WORKSPACE"
+          xmlatex name
+          # xmlatex frost $XM_TO_PROCESS   ### DONE ABOVE
+          xmlatex serve $XM_TO_PROCESS
+          echo "✅ Published to $XIMERA_URL$XIMERA_NAME "
+          echo "✅ Published to $XIMERA_URL$XIMERA_NAME " >> $GITHUB_STEP_SUMMARY
+
+      # - name: "Store artifacts"
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: serve
+      #     path: .
+
+  publish-ximera:
+    name: Run serve for public version
+    needs: serve-ximera-preview
+    runs-on: ubuntu-latest
+    if: github.ref == 'refs/heads/main'  
+    continue-on-error: true
+    container: *serve-container
+    environment: production
+
+    steps:
+
       - name: Checkout code
         uses: actions/checkout@v4
         with:
-          fetch-depth: 0   # full 
+          fetch-depth: 0
 
-      - name: Setup cache
-        uses: actions/cache@v4
+      # Download final artifact
+      - name: Restore artifacts from previous job
+        uses: actions/download-artifact@v4
         with:
-          path: | 
-            **/*.html
-            **/*.pdf
-            **/*.svg
-            **/*.aux
-            **/*.xref
-            **/*.toc
-            !xmPictures/**
-            !.git/**
-            !.github/**
-          key: ximera-${{ github.ref_name }}-${{ github.sha }}
-          restore-keys: |
-            ximera-${{ github.ref_name }}-
-            ximera-
+          name: htmlexport
+          path: .          
 
-
-      - name: Build and publish Ximera courses
+      - name: "XIMERA BUILD: Serve to ximeraserver (to public URL)"
         env:
-          GPG_KEY: ${{ secrets.GPG_KEY }}
-          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
-          XIMERA_URL: ${{ vars.XIMERA_URL }}
-          XIMERA_NAME: ${{ vars.XIMERA_NAME }}*${{ github.ref_name }}
-          # XMLATEX_OPTIONS: ${{ vars.XMLATEX_OPTIONS }}
-          XMLATEX_OPTIONS: "-j 4"
+          XIMERA_NAME: ${{ vars.XIMERA_NAME }}      
         run: |
-          ls -alrt
-          # git config --global --add safe.directory "$(pwd)"
-          # export COMMAND=./xmScripts/xmlatex.test
-          ./xmScripts/xmlatex veryclean $XMLATEX_OPTIONS
-          ./xmScripts/xmlatex bake --compile handout.pdf $XMLATEX_OPTIONS || echo NOK
-          ./xmScripts/xmlatex all $XMLATEX_OPTIONS
+          echo "Serving to $XIMERA_URL$XIMERA_NAME"
+          git config --global --add safe.directory "$GITHUB_WORKSPACE"          
+          xmlatex name
+          xmlatex serve  $XM_TO_PROCESS
+          # echo "Recent git log:"
+          # git log --oneline --graph --decorate --all -n 10
+          echo "✅ Published to $XIMERA_URL$XIMERA_NAME "
           echo "✅ Published to $XIMERA_URL$XIMERA_NAME " >> $GITHUB_STEP_SUMMARY
-
-      - name: Setup ximera serve cache (only .git)
-        id: serve-cache
-        uses: actions/cache/save@v4
-        with:
-          path: | 
-            xmScripts/**
-            .git/**
-          key: ximeraSERVE-${{ github.ref_name }}-${{ github.sha }}
-
-
-  publish-ximera:
-    name: Publish Ximera Courses
-    needs: build-ximera # Waits for the build job to complete
-    if: github.ref == 'refs/heads/main'
-    runs-on: ubuntu-latest
-    environment: production
-    steps:
-
-
-      - name: Restore ximera serve cache (only .git)
-        id: serve-cache-restore
-        uses: actions/cache/restore@v4
-        with:
-          fail-on-cache-miss: true
-          path: | 
-            xmScripts/**
-            .git/**
-          key: ximeraSERVE-${{ github.ref_name }}-${{ github.sha }}
-          
-      - name: Serve
-        env:
-          GPG_KEY: ${{ secrets.GPG_KEY }}
-          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
-          XIMERA_URL: ${{ vars.XIMERA_URL }}
-          XIMERA_NAME:  ${{ vars.XIMERA_NAME }}
-        run: |
-          ./xmScripts/xmlatex name         
-          ./xmScripts/xmlatex serve -f  # NOTE: -f  should not be needed ...        
-          echo "✅ Published to $XIMERA_URL$XIMERA_NAME " >> $GITHUB_STEP_SUMMARY
-
-
 
